### PR TITLE
Quickswitch patches

### PR DESCRIPTION
**Pull request by catharsis**
Two patches, the first merely cosmetic, the second a bit more interesting.

I'm also considering adding functionality for moving containers to workspaces. I initially thought that --move would help me out there, but it looks like I was mistaken. Is that something you might be interested in or do you have any argument as to why that might not be a good idea?

Thanks for a great project, I was very close to implementing pretty much the same thing myself before being informed of its existence.

### CODE REVIEW

**Comment by catharsis** [comment]
Going through my oustanding PRs. Since this hasn't received any attention since it was submitted, I'm guessing it's not a desired change, so I'm closing it.

**Comment by enkore** [comment]
Rebase your PR to https://github.com/OliverUv/quickswitch-for-i3/ , it's basically the official version now.

**Comment by catharsis** [comment]
@enkore Thank you, I will! :)

**Comment by OliverUv** [comment]
:)

**Pull request closed without merging**
